### ISSUE TITLE
Use mamba for examples?

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/software-skills-hpc-slides#4]
Conda is v. slow (especially so on the HPC). Mamba would help with this, but then we have to introduce another, unrelated topic during the course.

**Comment by adamltyson** [comment]
Will check how fast creating envs with conda is. If slow will move to mamba.

**Comment by adamltyson** [comment]
May also just require updating the conda module on HPC.

**Comment by alessandrofelder** [comment]
https://conda.org/blog/2023-07-05-conda-libmamba-solver-rollout/
According to the above blog written in July 2023, from Sep 2023 and `conda` 23.9.0 should come with a `solver=libmamba` as default, so this will/should go away without us intervening.

**Comment by adamltyson** [comment]
Closing, as the new version of conda should fix this.
